#!/bin/bash

~/Downloads/spark-1.6.1-bin-hadoop2.6/bin/spark-submit --class univ.bigdata.course.MainRunner --master local[*] target/spark-scala-maven-project-0.0.1-SNAPSHOT-jar-with-dependencies.jar 


